[package]
name = "ghostwire_types"
version = "0.2.1"
edition = "2021"

[dependencies]
bytemuck = {version = "1.18.0", features = ["derive"]}
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.64"
