[package]
name = "ghostwire-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
ghostwire-common = { path = "../ghostwire-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

network-types = "0.0.7"

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "ghostwire"
path = "src/main.rs"
