# From aya-template
# @see https://github.com/aya-rs/aya-template/blob/main/.github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: 00 4 * * *

env:
  CARGO_TERM_COLOR: always

jobs:
  ebpf:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: change directory to ebpf
        run: cd src/ebpf

      - uses: taiki-e/install-action@v2
        with:
          tool: bpf-linker

      - name: cargo xtask build
        working-directory: src/ebpf
        run: cargo run --package xtask -- build
